In [1]:
# dataset: Petrol_Consumption.csv
# Location: https://mitu.co.in/dataset

#### import the necessary libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### import the dataset

In [5]:
df = pd.read_csv('petrol_consumption.csv')
df.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

#### Separate input data and output data

In [6]:
# input
x = df.drop('Petrol_Consumption', axis = 1)

# output
y = df['Petrol_Consumption']

#### cross validation

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.25,
                                                   random_state=0)

In [9]:
x_train.shape

(36, 4)

In [11]:
x_test.shape

(12, 4)

#### Build the model

In [18]:
from sklearn.tree import DecisionTreeRegressor
reg = DecisionTreeRegressor(random_state= 0)

In [19]:
reg.fit(x_train,y_train)

DecisionTreeRegressor(random_state=0)

#### prediction on unseen data

In [20]:
y_pred = reg.predict(x_test)

In [21]:
y_pred

array([541., 498., 628., 628., 628., 644., 628., 649., 414., 464., 414.,
       628.])

In [22]:
result =pd.DataFrame({
    'actual': y_test,
    'predicted': y_pred
})

In [23]:
result

    actual  predicted
29     534      541.0
4      410      498.0
26     577      628.0
30     571      628.0
32     577      628.0
37     704      644.0
34     487      628.0
40     587      649.0
7      467      414.0
10     580      464.0
11     471      414.0
31     554      628.0

#### Performance Evaluation

In [24]:
# mean absolute error
np.mean(abs(y_test - y_pred))

68.08333333333333

In [29]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred) * 100

12.94003614849453

In [31]:
# mean squared error
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

5713.25

#### predict on unseen data

In [36]:
new = [[9.0, 3571, 1976, 0.839]]

In [37]:
reg.predict(new)

/home/aditya/anaconda3/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([640.])